#!/bin/bash

#PBS -l walltime=20:00:00
#PBS -l select=1:ncpus=48:mem=100gb

source ~/anaconda3/etc/profile.d/conda.sh

cd $PBS_O_WORKDIR
#mkdir /trialFolder # Failed
conda run -n R_envConda Rscript "$HOME/Strep_postThesis/R/3_pmcmc.R" --n_particles 10 --n_steps 1000 --run_stochastic true > "$HOME/Strep_postThesis/myresult.txt"
#mv *.pdf myresult.txt $PBS_O_WORKDIR

printenv > "$HOME/Strep_postThesis/myenv.txt"
#mv myenv.txt $PBS_O_WORKDIR
