#!/bin/bash

#PBS -N test
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=6:mem=5gb

# https://icl-rcs-user-guide.readthedocs.io/en/latest/hpc/pilot/cx3-phase2/#job-sizing-guidance

source ~/anaconda3/etc/profile.d/conda.sh

cd $PBS_O_WORKDIR
steps_folder = 800
conda run -n R_envConda Rscript "$HOME/Strep_postThesis/R/3_pmcmc.R" \
    --mode run_all \
    --n_particles 5 --n_steps "$steps_folder" \
    --run1_stochastic false --run2_stochastic false \
    --ncpus 6 \
    > "$HOME/Strep_postThesis/myresult.txt"

sleep 2
conda run -n R_envConda Rscript "$HOME/Strep_postThesis/R/4_post_pmcmc_pics.R" \
    --n_steps "$steps_folder"

sleep 2
conda run -n R_envConda Rscript "$HOME/Strep_postThesis/model/sir_stochastic_allAge_2post_pmcmc_picts.R" \
    --n_steps "$steps_folder"

printenv > "$HOME/Strep_postThesis/myenv.txt"


