#!/bin/bash

#PBS -N test
#PBS -l walltime=50:00:00
#PBS -l select=1:ncpus=6:mem=5gb

# https://icl-rcs-user-guide.readthedocs.io/en/latest/hpc/pilot/cx3-phase2/#job-sizing-guidance

source ~/anaconda3/etc/profile.d/conda.sh

cd $PBS_O_WORKDIR
#mkdir /trialFolder # Failed
conda run -n R_envConda Rscript "$HOME/Strep_postThesis/R/3_pmcmc.R" \
    --mode run_all \
    --n_particles 5 --n_steps 800 \
    --run1_stochastic false --run2_stochastic false \
    --ncpus 6 \
    > "$HOME/Strep_postThesis/myresult.txt"
#mv *.pdf myresult.txt $PBS_O_WORKDIR

printenv > "$HOME/Strep_postThesis/myenv.txt"
#mv myenv.txt $PBS_O_WORKDIR
